version: '3.8'
services:
  jenkins:
    environment:
      - DOCKER_REGISTRY=172.17.0.1:5000
    volumes:
      - ./data/jenkins:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock

  registry:
    volumes:
      - ./data/registry:/var/lib/registry

